-- Employee Management System for PostgreSQL
-- Run this file directly with:
-- psql -d your_database -f employee_management_system.sql

BEGIN;

DROP TABLE IF EXISTS employee_assets CASCADE;
DROP TABLE IF EXISTS assets CASCADE;
DROP TABLE IF EXISTS employee_training CASCADE;
DROP TABLE IF EXISTS training_programs CASCADE;
DROP TABLE IF EXISTS performance_reviews CASCADE;
DROP TABLE IF EXISTS payroll CASCADE;
DROP TABLE IF EXISTS leave_requests CASCADE;
DROP TABLE IF EXISTS attendance CASCADE;
DROP TABLE IF EXISTS employee_skills CASCADE;
DROP TABLE IF EXISTS skills CASCADE;
DROP TABLE IF EXISTS employee_project_assignments CASCADE;
DROP TABLE IF EXISTS projects CASCADE;
DROP TABLE IF EXISTS clients CASCADE;
DROP TABLE IF EXISTS employee_managers CASCADE;
DROP TABLE IF EXISTS employees CASCADE;
DROP TABLE IF EXISTS teams CASCADE;
DROP TABLE IF EXISTS departments CASCADE;
DROP TABLE IF EXISTS designations CASCADE;
DROP TABLE IF EXISTS offices CASCADE;
DROP TABLE IF EXISTS locations CASCADE;

CREATE TABLE locations (
    location_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    city VARCHAR(80) NOT NULL,
    state VARCHAR(80) NOT NULL,
    country VARCHAR(80) NOT NULL DEFAULT 'India',
    postal_code VARCHAR(10) NOT NULL CHECK (postal_code ~ '^[0-9]{6}$'),
    timezone VARCHAR(50) NOT NULL DEFAULT 'Asia/Kolkata',
    UNIQUE (city, state)
);

CREATE TABLE offices (
    office_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    location_id BIGINT NOT NULL REFERENCES locations(location_id) ON UPDATE CASCADE,
    office_code VARCHAR(20) NOT NULL UNIQUE,
    office_name VARCHAR(120) NOT NULL,
    address_line1 VARCHAR(180) NOT NULL,
    address_line2 VARCHAR(180),
    phone VARCHAR(15) NOT NULL CHECK (phone ~ '^[6-9][0-9]{9}$'),
    is_head_office BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE designations (
    designation_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(100) NOT NULL UNIQUE,
    level_no SMALLINT NOT NULL CHECK (level_no BETWEEN 1 AND 12),
    min_salary NUMERIC(12,2) NOT NULL CHECK (min_salary >= 0),
    max_salary NUMERIC(12,2) NOT NULL CHECK (max_salary >= min_salary)
);

CREATE TABLE departments (
    department_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    office_id BIGINT NOT NULL REFERENCES offices(office_id) ON UPDATE CASCADE,
    department_code VARCHAR(20) NOT NULL UNIQUE,
    department_name VARCHAR(100) NOT NULL UNIQUE,
    budget NUMERIC(14,2) NOT NULL DEFAULT 0 CHECK (budget >= 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE teams (
    team_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department_id BIGINT NOT NULL REFERENCES departments(department_id) ON UPDATE CASCADE,
    team_code VARCHAR(20) NOT NULL UNIQUE,
    team_name VARCHAR(100) NOT NULL,
    UNIQUE (department_id, team_name)
);

CREATE TABLE employees (
    employee_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_code VARCHAR(20) NOT NULL UNIQUE,
    first_name VARCHAR(80) NOT NULL,
    last_name VARCHAR(80) NOT NULL,
    gender VARCHAR(20) NOT NULL CHECK (gender IN ('Female','Male','Non-binary','Prefer not to say')),
    date_of_birth DATE NOT NULL CHECK (date_of_birth <= CURRENT_DATE - INTERVAL '18 years'),
    email VARCHAR(160) NOT NULL UNIQUE CHECK (email ~* '^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}$'),
    phone VARCHAR(15) NOT NULL UNIQUE CHECK (phone ~ '^[6-9][0-9]{9}$'),
    hire_date DATE NOT NULL CHECK (hire_date <= CURRENT_DATE),
    department_id BIGINT NOT NULL REFERENCES departments(department_id) ON UPDATE CASCADE,
    team_id BIGINT NOT NULL REFERENCES teams(team_id) ON UPDATE CASCADE,
    designation_id BIGINT NOT NULL REFERENCES designations(designation_id) ON UPDATE CASCADE,
    office_id BIGINT NOT NULL REFERENCES offices(office_id) ON UPDATE CASCADE,
    employment_status VARCHAR(20) NOT NULL DEFAULT 'Active' CHECK (employment_status IN ('Active','On Leave','Resigned','Terminated')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE employee_managers (
    manager_relation_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT NOT NULL REFERENCES employees(employee_id) ON DELETE CASCADE,
    manager_id BIGINT NOT NULL REFERENCES employees(employee_id) ON DELETE RESTRICT,
    effective_from DATE NOT NULL,
    effective_to DATE,
    CHECK (employee_id <> manager_id),
    CHECK (effective_to IS NULL OR effective_to >= effective_from)
);

CREATE TABLE clients (
    client_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_code VARCHAR(20) NOT NULL UNIQUE,
    client_name VARCHAR(140) NOT NULL UNIQUE,
    industry VARCHAR(80) NOT NULL,
    location_id BIGINT NOT NULL REFERENCES locations(location_id) ON UPDATE CASCADE,
    contact_email VARCHAR(160) NOT NULL UNIQUE CHECK (contact_email ~* '^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}$'),
    contact_phone VARCHAR(15) NOT NULL CHECK (contact_phone ~ '^[6-9][0-9]{9}$')
);

CREATE TABLE projects (
    project_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id BIGINT NOT NULL REFERENCES clients(client_id) ON UPDATE CASCADE,
    department_id BIGINT NOT NULL REFERENCES departments(department_id) ON UPDATE CASCADE,
    project_code VARCHAR(20) NOT NULL UNIQUE,
    project_name VARCHAR(160) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE,
    status VARCHAR(20) NOT NULL DEFAULT 'Planned' CHECK (status IN ('Planned','Active','On Hold','Completed','Cancelled')),
    budget NUMERIC(14,2) NOT NULL DEFAULT 0 CHECK (budget >= 0),
    current_assignment_count INTEGER NOT NULL DEFAULT 0 CHECK (current_assignment_count >= 0),
    CHECK (end_date IS NULL OR end_date >= start_date)
);

CREATE TABLE employee_project_assignments (
    assignment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT NOT NULL REFERENCES employees(employee_id) ON DELETE CASCADE,
    project_id BIGINT NOT NULL REFERENCES projects(project_id) ON DELETE CASCADE,
    role_on_project VARCHAR(80) NOT NULL,
    allocation_percent NUMERIC(5,2) NOT NULL CHECK (allocation_percent > 0 AND allocation_percent <= 100),
    assigned_from DATE NOT NULL,
    assigned_to DATE,
    billable BOOLEAN NOT NULL DEFAULT TRUE,
    CHECK (assigned_to IS NULL OR assigned_to >= assigned_from),
    UNIQUE (employee_id, project_id, assigned_from)
);

CREATE TABLE skills (
    skill_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    skill_name VARCHAR(100) NOT NULL UNIQUE,
    skill_category VARCHAR(80) NOT NULL
);

CREATE TABLE employee_skills (
    employee_skill_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT NOT NULL REFERENCES employees(employee_id) ON DELETE CASCADE,
    skill_id BIGINT NOT NULL REFERENCES skills(skill_id) ON DELETE CASCADE,
    proficiency_level VARCHAR(20) NOT NULL CHECK (proficiency_level IN ('Beginner','Intermediate','Advanced','Expert')),
    years_experience NUMERIC(4,1) NOT NULL DEFAULT 0 CHECK (years_experience >= 0),
    certified BOOLEAN NOT NULL DEFAULT FALSE,
    UNIQUE (employee_id, skill_id)
);

CREATE TABLE attendance (
    attendance_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT NOT NULL REFERENCES employees(employee_id) ON DELETE CASCADE,
    attendance_date DATE NOT NULL,
    check_in TIME,
    check_out TIME,
    status VARCHAR(20) NOT NULL CHECK (status IN ('Present','Absent','Half Day','Work From Home','Holiday')),
    total_hours NUMERIC(4,2) NOT NULL DEFAULT 0 CHECK (total_hours >= 0 AND total_hours <= 24),
    UNIQUE (employee_id, attendance_date),
    CHECK (check_out IS NULL OR check_in IS NULL OR check_out >= check_in)
);

CREATE TABLE leave_requests (
    leave_request_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT NOT NULL REFERENCES employees(employee_id) ON DELETE CASCADE,
    approver_id BIGINT REFERENCES employees(employee_id) ON DELETE SET NULL,
    leave_type VARCHAR(30) NOT NULL CHECK (leave_type IN ('Casual','Sick','Earned','Maternity','Paternity','Bereavement','Unpaid')),
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    reason TEXT,
    status VARCHAR(20) NOT NULL DEFAULT 'Pending' CHECK (status IN ('Pending','Approved','Rejected','Cancelled')),
    requested_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (end_date >= start_date),
    CHECK (approver_id IS NULL OR approver_id <> employee_id)
);

CREATE TABLE payroll (
    payroll_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT NOT NULL REFERENCES employees(employee_id) ON DELETE CASCADE,
    payroll_month DATE NOT NULL,
    basic_salary NUMERIC(12,2) NOT NULL CHECK (basic_salary >= 0),
    hra NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (hra >= 0),
    allowances NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (allowances >= 0),
    deductions NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (deductions >= 0),
    net_salary NUMERIC(12,2) GENERATED ALWAYS AS (basic_salary + hra + allowances - deductions) STORED,
    payment_status VARCHAR(20) NOT NULL DEFAULT 'Pending' CHECK (payment_status IN ('Pending','Paid','On Hold')),
    paid_on DATE,
    UNIQUE (employee_id, payroll_month)
);

CREATE TABLE performance_reviews (
    review_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT NOT NULL REFERENCES employees(employee_id) ON DELETE CASCADE,
    reviewer_id BIGINT NOT NULL REFERENCES employees(employee_id) ON DELETE RESTRICT,
    review_period_start DATE NOT NULL,
    review_period_end DATE NOT NULL,
    rating NUMERIC(3,2) NOT NULL CHECK (rating >= 1 AND rating <= 5),
    goals_met_percent NUMERIC(5,2) NOT NULL CHECK (goals_met_percent >= 0 AND goals_met_percent <= 100),
    comments TEXT,
    reviewed_at DATE NOT NULL DEFAULT CURRENT_DATE,
    CHECK (review_period_end >= review_period_start),
    CHECK (employee_id <> reviewer_id)
);

CREATE TABLE training_programs (
    training_program_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department_id BIGINT NOT NULL REFERENCES departments(department_id) ON UPDATE CASCADE,
    program_code VARCHAR(20) NOT NULL UNIQUE,
    program_name VARCHAR(140) NOT NULL,
    provider VARCHAR(120) NOT NULL,
    duration_hours NUMERIC(5,2) NOT NULL CHECK (duration_hours > 0),
    mode VARCHAR(20) NOT NULL CHECK (mode IN ('Online','Classroom','Hybrid'))
);

CREATE TABLE employee_training (
    employee_training_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT NOT NULL REFERENCES employees(employee_id) ON DELETE CASCADE,
    training_program_id BIGINT NOT NULL REFERENCES training_programs(training_program_id) ON DELETE CASCADE,
    enrolled_on DATE NOT NULL,
    completed_on DATE,
    status VARCHAR(20) NOT NULL DEFAULT 'Enrolled' CHECK (status IN ('Enrolled','In Progress','Completed','Dropped')),
    score NUMERIC(5,2) CHECK (score IS NULL OR (score >= 0 AND score <= 100)),
    CHECK (completed_on IS NULL OR completed_on >= enrolled_on),
    UNIQUE (employee_id, training_program_id, enrolled_on)
);

CREATE TABLE assets (
    asset_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    office_id BIGINT NOT NULL REFERENCES offices(office_id) ON UPDATE CASCADE,
    asset_tag VARCHAR(40) NOT NULL UNIQUE,
    asset_type VARCHAR(50) NOT NULL,
    brand VARCHAR(60) NOT NULL,
    model VARCHAR(80) NOT NULL,
    serial_number VARCHAR(80) NOT NULL UNIQUE,
    purchase_date DATE NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'Available' CHECK (status IN ('Available','Assigned','Repair','Retired'))
);

CREATE TABLE employee_assets (
    employee_asset_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT NOT NULL REFERENCES employees(employee_id) ON DELETE CASCADE,
    asset_id BIGINT NOT NULL REFERENCES assets(asset_id) ON DELETE RESTRICT,
    assigned_on DATE NOT NULL,
    returned_on DATE,
    condition_on_issue VARCHAR(20) NOT NULL CHECK (condition_on_issue IN ('New','Good','Fair')),
    condition_on_return VARCHAR(20) CHECK (condition_on_return IS NULL OR condition_on_return IN ('Good','Fair','Damaged')),
    CHECK (returned_on IS NULL OR returned_on >= assigned_on)
);

CREATE UNIQUE INDEX ux_employee_managers_current ON employee_managers(employee_id) WHERE effective_to IS NULL;
CREATE UNIQUE INDEX ux_employee_assets_current ON employee_assets(asset_id) WHERE returned_on IS NULL;
CREATE INDEX idx_offices_location_id ON offices(location_id);
CREATE INDEX idx_departments_office_id ON departments(office_id);
CREATE INDEX idx_teams_department_id ON teams(department_id);
CREATE INDEX idx_employees_department_id ON employees(department_id);
CREATE INDEX idx_employees_team_id ON employees(team_id);
CREATE INDEX idx_employees_designation_id ON employees(designation_id);
CREATE INDEX idx_employees_office_id ON employees(office_id);
CREATE INDEX idx_employees_name ON employees(last_name, first_name);
CREATE INDEX idx_clients_location_id ON clients(location_id);
CREATE INDEX idx_projects_client_id ON projects(client_id);
CREATE INDEX idx_projects_department_status ON projects(department_id, status);
CREATE INDEX idx_assignments_employee_id ON employee_project_assignments(employee_id);
CREATE INDEX idx_assignments_project_id ON employee_project_assignments(project_id);
CREATE INDEX idx_employee_skills_skill_id ON employee_skills(skill_id);
CREATE INDEX idx_attendance_employee_date ON attendance(employee_id, attendance_date);
CREATE INDEX idx_leave_employee_status ON leave_requests(employee_id, status);
CREATE INDEX idx_payroll_month ON payroll(payroll_month);
CREATE INDEX idx_reviews_employee_period ON performance_reviews(employee_id, review_period_start, review_period_end);
CREATE INDEX idx_training_employee_status ON employee_training(employee_id, status);
CREATE INDEX idx_assets_office_status ON assets(office_id, status);

-- Master data and sample data.
INSERT INTO locations (location_id, city, state, country, postal_code, timezone) VALUES
(1,'Bengaluru','Karnataka','India','560001','Asia/Kolkata'),
(2,'Hyderabad','Telangana','India','500081','Asia/Kolkata'),
(3,'Pune','Maharashtra','India','411001','Asia/Kolkata'),
(4,'Chennai','Tamil Nadu','India','600001','Asia/Kolkata'),
(5,'Mumbai','Maharashtra','India','400001','Asia/Kolkata'),
(6,'Delhi','Delhi','India','110001','Asia/Kolkata'),
(7,'Gurugram','Haryana','India','122001','Asia/Kolkata'),
(8,'Noida','Uttar Pradesh','India','201301','Asia/Kolkata'),
(9,'Kolkata','West Bengal','India','700001','Asia/Kolkata'),
(10,'Ahmedabad','Gujarat','India','380001','Asia/Kolkata');

INSERT INTO offices (office_id, location_id, office_code, office_name, address_line1, address_line2, phone, is_head_office) VALUES
(1,1,'BLR-HQ','Bengaluru Head Office','MG Road Business Centre','Near Trinity Metro','8045678901',TRUE),
(2,2,'HYD-TEC','Hyderabad Technology Office','HITEC City Main Road','Madhapur','8045678902',FALSE),
(3,3,'PUN-DEV','Pune Development Centre','Baner Road','Balewadi','8045678903',FALSE),
(4,4,'CHN-OPS','Chennai Operations Office','OMR IT Corridor','Thoraipakkam','8045678904',FALSE),
(5,7,'GGN-SLS','Gurugram Sales Office','Cyber City Phase II','DLF','8045678905',FALSE);

INSERT INTO designations (designation_id, title, level_no, min_salary, max_salary) VALUES
(1,'Associate Software Engineer',1,450000,800000),
(2,'Software Engineer',2,700000,1400000),
(3,'Senior Software Engineer',3,1200000,2200000),
(4,'Lead Engineer',4,2000000,3200000),
(5,'Engineering Manager',5,2800000,4500000),
(6,'Product Manager',4,1800000,3500000),
(7,'QA Engineer',2,600000,1300000),
(8,'HR Business Partner',3,800000,1800000),
(9,'Finance Analyst',2,700000,1600000),
(10,'Sales Manager',4,1500000,3000000),
(11,'Data Analyst',2,700000,1500000),
(12,'Data Scientist',3,1200000,2600000);

INSERT INTO departments (department_id, office_id, department_code, department_name, budget) VALUES
(1,1,'DEP01','Engineering',10000000),
(2,1,'DEP02','Product',7500000),
(3,2,'DEP03','Quality Assurance',5000000),
(4,4,'DEP04','Human Resources',3500000),
(5,5,'DEP05','Finance',5000000),
(6,5,'DEP06','Sales',9000000),
(7,5,'DEP07','Marketing',6000000),
(8,4,'DEP08','Customer Success',4500000),
(9,2,'DEP09','IT Operations',6500000),
(10,3,'DEP10','Data Analytics',8000000);

INSERT INTO teams (team_id, department_id, team_code, team_name) VALUES
(1,1,'TM01','Platform'), (2,1,'TM02','Backend Services'),
(3,2,'TM03','Product Strategy'), (4,2,'TM04','UX Research'),
(5,3,'TM05','Automation QA'), (6,3,'TM06','Release QA'),
(7,4,'TM07','People Ops'), (8,4,'TM08','Talent Acquisition'),
(9,5,'TM09','Accounting'), (10,5,'TM10','Compliance'),
(11,6,'TM11','Enterprise Sales'), (12,6,'TM12','Inside Sales'),
(13,7,'TM13','Demand Generation'), (14,7,'TM14','Content'),
(15,8,'TM15','Support Engineering'), (16,8,'TM16','Implementation'),
(17,9,'TM17','Infrastructure'), (18,9,'TM18','Security'),
(19,10,'TM19','Business Intelligence'), (20,10,'TM20','Data Science');

INSERT INTO employees (
    employee_id, employee_code, first_name, last_name, gender, date_of_birth, email, phone,
    hire_date, department_id, team_id, designation_id, office_id, employment_status
)
SELECT
    gs,
    'EMP' || LPAD(gs::text, 4, '0'),
    CASE WHEN gs % 2 = 0
         THEN (ARRAY['Ananya','Priya','Neha','Sneha','Aditi','Kavya','Meera','Riya','Pooja','Swati','Isha','Nisha','Divya','Shruti','Aishwarya','Tanvi','Sakshi','Radhika','Nandini','Vaishnavi'])[1 + (gs % 20)]
         ELSE (ARRAY['Aarav','Vivaan','Aditya','Arjun','Sai','Rohan','Rahul','Karan','Vikram','Siddharth','Nikhil','Pranav','Kunal','Manish','Suresh','Rakesh','Ankit','Deepak','Gaurav','Harsh'])[1 + (gs % 20)]
    END,
    (ARRAY['Sharma','Verma','Iyer','Nair','Reddy','Rao','Patel','Mehta','Gupta','Singh','Kumar','Das','Bose','Chatterjee','Mukherjee','Joshi','Kulkarni','Desai','Menon','Pillai'])[1 + (gs % 20)],
    CASE WHEN gs % 2 = 0 THEN 'Female' ELSE 'Male' END,
    DATE '1978-01-01' + ((gs * 53) % 9000),
    LOWER('employee' || gs || '@bharatems.example.com'),
    '9' || LPAD((700000000 + gs)::text, 9, '0'),
    DATE '2016-01-01' + ((gs * 29) % 3600),
    ((gs - 1) % 10) + 1,
    (((gs - 1) % 10) * 2) + CASE WHEN gs % 2 = 0 THEN 2 ELSE 1 END,
    CASE
        WHEN gs <= 10 THEN 5
        WHEN ((gs - 1) % 10) + 1 = 2 THEN 6
        WHEN ((gs - 1) % 10) + 1 = 3 THEN 7
        WHEN ((gs - 1) % 10) + 1 = 4 THEN 8
        WHEN ((gs - 1) % 10) + 1 = 5 THEN 9
        WHEN ((gs - 1) % 10) + 1 = 6 THEN 10
        WHEN ((gs - 1) % 10) + 1 = 10 THEN 11 + (gs % 2)
        ELSE 1 + (gs % 4)
    END,
    (SELECT office_id FROM departments d WHERE d.department_id = ((gs - 1) % 10) + 1),
    'Active'
FROM generate_series(1, 200) AS gs;

INSERT INTO employee_managers (manager_relation_id, employee_id, manager_id, effective_from)
SELECT gs - 1, gs, CASE WHEN gs <= 20 THEN 1 ELSE ((gs - 2) % 10) + 1 END, DATE '2021-04-01'
FROM generate_series(2, 200) AS gs;

INSERT INTO clients (client_id, client_code, client_name, industry, location_id, contact_email, contact_phone)
SELECT
    gs,
    'CL' || LPAD(gs::text, 3, '0'),
    (ARRAY['Aarohan','Bharat','Crescent','Dakshin','Eastern','Fortune','Ganga','Horizon','Indus','Jeevan','Konark','Lotus','Meridian','Narmada','Orchid','Pragati','Quantum','Riverstone','Saffron','Triveni','Udaan','Vistaar','Western','Yukti','Zenith'])[gs] || ' ' ||
    (ARRAY['Technologies','Industries','Bank','Retail','Health','Logistics'])[1 + (gs % 6)],
    (ARRAY['Banking','Insurance','Retail','Healthcare','Education','Manufacturing','Telecom','Logistics','Energy','Government','FinTech','E-commerce'])[1 + (gs % 12)],
    ((gs - 1) % 10) + 1,
    'procurement' || LPAD(gs::text, 3, '0') || '@client.example.in',
    '8' || LPAD((600000000 + gs)::text, 9, '0')
FROM generate_series(1, 25) AS gs;

INSERT INTO projects (project_id, client_id, department_id, project_code, project_name, start_date, end_date, status, budget)
SELECT
    gs,
    ((gs - 1) % 25) + 1,
    ((gs - 1) % 10) + 1,
    'PRJ' || LPAD(gs::text, 4, '0'),
    (ARRAY['Nova','Astra','Prism','Setu','Tejas','Mitra','Utsav','Nexus','Sparsh','Drishti'])[1 + (gs % 10)] || ' ' ||
    (ARRAY['ERP','CRM','Analytics','Payments','Mobile','Cloud','Automation'])[1 + (gs % 7)] || ' ' || LPAD(gs::text, 2, '0'),
    DATE '2024-01-01' + (gs * 11),
    CASE WHEN gs % 5 = 4 THEN DATE '2024-01-01' + (gs * 11) + 240 ELSE NULL END,
    (ARRAY['Planned','Active','Active','On Hold','Completed'])[1 + (gs % 5)],
    (15 + (gs % 100)) * 100000
FROM generate_series(1, 50) AS gs;

INSERT INTO employee_project_assignments (assignment_id, employee_id, project_id, role_on_project, allocation_percent, assigned_from, assigned_to, billable)
SELECT
    gs,
    ((gs - 1) % 200) + 1,
    ((gs * 7 - 1) % 50) + 1,
    (ARRAY['Developer','QA Analyst','Scrum Master','Business Analyst','Data Engineer','DevOps Engineer','UI Designer','Tech Lead','Support Engineer','Product Owner'])[1 + (gs % 10)],
    (ARRAY[25,50,75,100])[1 + (gs % 4)],
    DATE '2025-01-01' + ((gs % 12) * 28),
    CASE WHEN gs % 3 = 0 THEN DATE '2025-01-01' + ((gs % 12) * 28) + 120 ELSE NULL END,
    gs % 6 <> 0
FROM generate_series(1, 500) AS gs;

INSERT INTO skills (skill_id, skill_name, skill_category) VALUES
(1,'PostgreSQL','Database'),(2,'Python','Programming'),(3,'Java','Programming'),(4,'React','Frontend'),(5,'Angular','Frontend'),
(6,'AWS','Cloud'),(7,'Azure','Cloud'),(8,'Docker','DevOps'),(9,'Kubernetes','DevOps'),(10,'Terraform','DevOps'),
(11,'Power BI','Analytics'),(12,'Tableau','Analytics'),(13,'Machine Learning','AI'),(14,'Manual Testing','QA'),(15,'Selenium','QA'),
(16,'JMeter','QA'),(17,'Product Discovery','Product'),(18,'Agile Coaching','Delivery'),(19,'Payroll Compliance','HR'),(20,'Recruiting','HR'),
(21,'Financial Reporting','Finance'),(22,'GST Compliance','Finance'),(23,'Enterprise Sales','Sales'),(24,'Digital Marketing','Marketing'),(25,'Customer Onboarding','Support'),
(26,'Cybersecurity','Security'),(27,'Linux Administration','IT'),(28,'Data Warehousing','Data'),(29,'API Design','Engineering'),(30,'Microservices','Engineering');

INSERT INTO employee_skills (employee_skill_id, employee_id, skill_id, proficiency_level, years_experience, certified)
SELECT
    gs,
    ((gs - 1) % 200) + 1,
    (((gs - 1) / 200) * 7 + ((gs - 1) % 30)) % 30 + 1,
    (ARRAY['Beginner','Intermediate','Advanced','Expert'])[1 + (gs % 4)],
    ROUND((0.5 + (gs % 90) / 10.0)::numeric, 1),
    gs % 3 = 0
FROM generate_series(1, 400) AS gs;

INSERT INTO attendance (attendance_id, employee_id, attendance_date, check_in, check_out, status, total_hours)
SELECT
    ((d.day_no - 1) * 200) + e.employee_id,
    e.employee_id,
    DATE '2026-01-01' + (d.day_no - 1),
    CASE WHEN EXTRACT(ISODOW FROM DATE '2026-01-01' + (d.day_no - 1)) IN (6,7) OR (e.employee_id + d.day_no) % 19 = 0 THEN NULL ELSE TIME '09:30' END,
    CASE WHEN EXTRACT(ISODOW FROM DATE '2026-01-01' + (d.day_no - 1)) IN (6,7) OR (e.employee_id + d.day_no) % 19 = 0 THEN NULL
         WHEN (e.employee_id + d.day_no) % 11 = 0 THEN TIME '13:30' ELSE TIME '18:30' END,
    CASE WHEN EXTRACT(ISODOW FROM DATE '2026-01-01' + (d.day_no - 1)) IN (6,7) THEN 'Holiday'
         WHEN (e.employee_id + d.day_no) % 19 = 0 THEN 'Absent'
         WHEN (e.employee_id + d.day_no) % 13 = 0 THEN 'Work From Home'
         WHEN (e.employee_id + d.day_no) % 11 = 0 THEN 'Half Day'
         ELSE 'Present' END,
    CASE WHEN EXTRACT(ISODOW FROM DATE '2026-01-01' + (d.day_no - 1)) IN (6,7) OR (e.employee_id + d.day_no) % 19 = 0 THEN 0
         WHEN (e.employee_id + d.day_no) % 11 = 0 THEN 4 ELSE 9 END
FROM generate_series(1, 25) AS d(day_no)
CROSS JOIN employees e;

INSERT INTO leave_requests (leave_request_id, employee_id, approver_id, leave_type, start_date, end_date, reason, status)
SELECT
    gs,
    ((gs - 1) % 200) + 1,
    CASE WHEN ((gs - 1) % 200) + 1 = 1 THEN 2 ELSE 1 END,
    (ARRAY['Casual','Sick','Earned','Maternity','Paternity','Bereavement','Unpaid'])[1 + (gs % 7)],
    DATE '2025-01-01' + ((gs % 300)),
    DATE '2025-01-01' + ((gs % 300)) + (gs % 5),
    (ARRAY['Personal work','Medical appointment','Family function','Travel','Health rest','Emergency'])[1 + (gs % 6)],
    (ARRAY['Pending','Approved','Approved','Rejected','Cancelled'])[1 + (gs % 5)]
FROM generate_series(1, 500) AS gs;

INSERT INTO payroll (payroll_id, employee_id, payroll_month, basic_salary, hra, allowances, deductions, payment_status, paid_on)
SELECT
    e.employee_id,
    e.employee_id,
    DATE '2026-01-01',
    45000 + (e.designation_id * 9000) + (e.employee_id % 20) * 1000,
    (45000 + (e.designation_id * 9000) + (e.employee_id % 20) * 1000) * 0.40,
    5000 + (e.employee_id % 10) * 1500,
    2500 + (e.employee_id % 8) * 900,
    CASE WHEN e.employee_id % 12 = 0 THEN 'Pending' ELSE 'Paid' END,
    CASE WHEN e.employee_id % 12 = 0 THEN NULL ELSE DATE '2026-01-31' END
FROM employees e;

INSERT INTO performance_reviews (review_id, employee_id, reviewer_id, review_period_start, review_period_end, rating, goals_met_percent, comments, reviewed_at)
SELECT
    gs,
    ((gs - 1) % 199) + 2,
    1,
    CASE WHEN gs % 2 = 0 THEN DATE '2025-07-01' ELSE DATE '2025-01-01' END,
    CASE WHEN gs % 2 = 0 THEN DATE '2025-12-31' ELSE DATE '2025-06-30' END,
    ROUND((2.5 + ((gs % 25) / 10.0))::numeric, 2),
    60 + (gs % 40),
    (ARRAY['Consistently delivers strong outcomes.','Shows good ownership and collaboration.','Needs deeper focus on documentation.','Ready for higher responsibility.'])[1 + (gs % 4)],
    DATE '2026-01-15'
FROM generate_series(1, 300) AS gs;

INSERT INTO training_programs (training_program_id, department_id, program_code, program_name, provider, duration_hours, mode)
SELECT
    gs,
    ((gs - 1) % 10) + 1,
    'TRN' || LPAD(gs::text, 3, '0'),
    (ARRAY['Advanced','Applied','Foundation','Professional'])[1 + (gs % 4)] || ' ' ||
    (ARRAY['PostgreSQL','Python','Cloud Architecture','Agile Delivery','Data Analytics','Leadership','Security','Testing','Finance Controls','Customer Success'])[1 + (gs % 10)],
    (ARRAY['Infosys Springboard','NPTEL','Coursera','UpGrad','Internal Academy'])[1 + (gs % 5)],
    (ARRAY[8,12,16,24,32,40])[1 + (gs % 6)],
    (ARRAY['Online','Classroom','Hybrid'])[1 + (gs % 3)]
FROM generate_series(1, 30) AS gs;

INSERT INTO employee_training (employee_training_id, employee_id, training_program_id, enrolled_on, completed_on, status, score)
SELECT
    gs,
    ((gs - 1) % 200) + 1,
    ((gs * 7 - 1) % 30) + 1,
    DATE '2025-01-01' + (gs % 300),
    CASE WHEN gs % 4 IN (0,1) THEN DATE '2025-01-01' + (gs % 300) + 30 ELSE NULL END,
    (ARRAY['Completed','Completed','In Progress','Enrolled','Dropped'])[1 + (gs % 5)],
    CASE WHEN gs % 4 IN (0,1) THEN 60 + (gs % 39) ELSE NULL END
FROM generate_series(1, 300) AS gs;

INSERT INTO assets (asset_id, office_id, asset_tag, asset_type, brand, model, serial_number, purchase_date, status)
SELECT
    gs,
    ((gs - 1) % 5) + 1,
    'AST' || LPAD(gs::text, 5, '0'),
    (ARRAY['Laptop','Monitor','Keyboard','Mouse','Headset','Phone','ID Card','Docking Station'])[1 + (gs % 8)],
    (ARRAY['Dell','HP','Lenovo','Apple','Samsung','Logitech','Jabra','OnePlus'])[1 + (gs % 8)],
    'Model-' || LPAD(gs::text, 4, '0'),
    'SN2026' || LPAD(gs::text, 6, '0'),
    DATE '2023-01-01' + (gs % 900),
    CASE WHEN gs <= 200 THEN 'Assigned' WHEN gs % 7 = 0 THEN 'Repair' ELSE 'Available' END
FROM generate_series(1, 250) AS gs;

INSERT INTO employee_assets (employee_asset_id, employee_id, asset_id, assigned_on, returned_on, condition_on_issue, condition_on_return)
SELECT gs, gs, gs, DATE '2025-01-01' + (gs % 300), NULL, (ARRAY['New','Good','Fair'])[1 + (gs % 3)], NULL
FROM generate_series(1, 200) AS gs;

UPDATE projects p
SET current_assignment_count = c.assignment_count
FROM (
    SELECT project_id, COUNT(*) AS assignment_count
    FROM employee_project_assignments
    WHERE assigned_to IS NULL OR assigned_to >= CURRENT_DATE
    GROUP BY project_id
) c
WHERE p.project_id = c.project_id;

SELECT setval(pg_get_serial_sequence('locations','location_id'), (SELECT MAX(location_id) FROM locations));
SELECT setval(pg_get_serial_sequence('offices','office_id'), (SELECT MAX(office_id) FROM offices));
SELECT setval(pg_get_serial_sequence('designations','designation_id'), (SELECT MAX(designation_id) FROM designations));
SELECT setval(pg_get_serial_sequence('departments','department_id'), (SELECT MAX(department_id) FROM departments));
SELECT setval(pg_get_serial_sequence('teams','team_id'), (SELECT MAX(team_id) FROM teams));
SELECT setval(pg_get_serial_sequence('employees','employee_id'), (SELECT MAX(employee_id) FROM employees));
SELECT setval(pg_get_serial_sequence('employee_managers','manager_relation_id'), (SELECT MAX(manager_relation_id) FROM employee_managers));
SELECT setval(pg_get_serial_sequence('clients','client_id'), (SELECT MAX(client_id) FROM clients));
SELECT setval(pg_get_serial_sequence('projects','project_id'), (SELECT MAX(project_id) FROM projects));
SELECT setval(pg_get_serial_sequence('employee_project_assignments','assignment_id'), (SELECT MAX(assignment_id) FROM employee_project_assignments));
SELECT setval(pg_get_serial_sequence('skills','skill_id'), (SELECT MAX(skill_id) FROM skills));
SELECT setval(pg_get_serial_sequence('employee_skills','employee_skill_id'), (SELECT MAX(employee_skill_id) FROM employee_skills));
SELECT setval(pg_get_serial_sequence('attendance','attendance_id'), (SELECT MAX(attendance_id) FROM attendance));
SELECT setval(pg_get_serial_sequence('leave_requests','leave_request_id'), (SELECT MAX(leave_request_id) FROM leave_requests));
SELECT setval(pg_get_serial_sequence('payroll','payroll_id'), (SELECT MAX(payroll_id) FROM payroll));
SELECT setval(pg_get_serial_sequence('performance_reviews','review_id'), (SELECT MAX(review_id) FROM performance_reviews));
SELECT setval(pg_get_serial_sequence('training_programs','training_program_id'), (SELECT MAX(training_program_id) FROM training_programs));
SELECT setval(pg_get_serial_sequence('employee_training','employee_training_id'), (SELECT MAX(employee_training_id) FROM employee_training));
SELECT setval(pg_get_serial_sequence('assets','asset_id'), (SELECT MAX(asset_id) FROM assets));
SELECT setval(pg_get_serial_sequence('employee_assets','employee_asset_id'), (SELECT MAX(employee_asset_id) FROM employee_assets));

-- Views.
CREATE OR REPLACE VIEW vw_employee_directory AS
SELECT e.employee_id, e.employee_code, e.first_name || ' ' || e.last_name AS employee_name,
       e.email, e.phone, d.department_name, t.team_name, g.title AS designation,
       o.office_name, l.city, l.state, e.employment_status
FROM employees e
JOIN departments d ON d.department_id = e.department_id
JOIN teams t ON t.team_id = e.team_id
JOIN designations g ON g.designation_id = e.designation_id
JOIN offices o ON o.office_id = e.office_id
JOIN locations l ON l.location_id = o.location_id;

CREATE OR REPLACE VIEW vw_employee_hierarchy AS
SELECT e.employee_id, e.employee_code, e.first_name || ' ' || e.last_name AS employee_name,
       m.employee_id AS manager_employee_id, m.employee_code AS manager_code,
       m.first_name || ' ' || m.last_name AS manager_name, em.effective_from
FROM employee_managers em
JOIN employees e ON e.employee_id = em.employee_id
JOIN employees m ON m.employee_id = em.manager_id
WHERE em.effective_to IS NULL;

CREATE OR REPLACE VIEW vw_project_allocation_summary AS
SELECT p.project_id, p.project_code, p.project_name, c.client_name, d.department_name,
       p.status, COUNT(epa.assignment_id) AS assignment_count,
       COALESCE(SUM(epa.allocation_percent),0) AS total_allocation_percent
FROM projects p
JOIN clients c ON c.client_id = p.client_id
JOIN departments d ON d.department_id = p.department_id
LEFT JOIN employee_project_assignments epa ON epa.project_id = p.project_id
GROUP BY p.project_id, p.project_code, p.project_name, c.client_name, d.department_name, p.status;

CREATE OR REPLACE VIEW vw_monthly_attendance_summary AS
SELECT e.employee_id, e.employee_code, e.first_name || ' ' || e.last_name AS employee_name,
       date_trunc('month', a.attendance_date)::date AS attendance_month,
       COUNT(*) FILTER (WHERE a.status = 'Present') AS present_days,
       COUNT(*) FILTER (WHERE a.status = 'Work From Home') AS wfh_days,
       COUNT(*) FILTER (WHERE a.status = 'Absent') AS absent_days,
       COUNT(*) FILTER (WHERE a.status = 'Half Day') AS half_days,
       SUM(a.total_hours) AS total_hours
FROM attendance a
JOIN employees e ON e.employee_id = a.employee_id
GROUP BY e.employee_id, e.employee_code, employee_name, date_trunc('month', a.attendance_date)::date;

CREATE OR REPLACE VIEW vw_payroll_cost_by_department AS
SELECT d.department_id, d.department_name, p.payroll_month,
       COUNT(p.payroll_id) AS employees_paid,
       SUM(p.basic_salary) AS total_basic,
       SUM(p.hra + p.allowances) AS total_benefits,
       SUM(p.deductions) AS total_deductions,
       SUM(p.net_salary) AS total_net_salary
FROM payroll p
JOIN employees e ON e.employee_id = p.employee_id
JOIN departments d ON d.department_id = e.department_id
GROUP BY d.department_id, d.department_name, p.payroll_month;

-- Stored procedures.
CREATE OR REPLACE PROCEDURE sp_assign_employee_to_project(
    p_employee_id BIGINT, p_project_id BIGINT, p_role_on_project VARCHAR,
    p_allocation_percent NUMERIC, p_assigned_from DATE, p_billable BOOLEAN DEFAULT TRUE
)
LANGUAGE plpgsql AS $$
BEGIN
    INSERT INTO employee_project_assignments (employee_id, project_id, role_on_project, allocation_percent, assigned_from, billable)
    VALUES (p_employee_id, p_project_id, p_role_on_project, p_allocation_percent, p_assigned_from, p_billable);
END;
$$;

CREATE OR REPLACE PROCEDURE sp_submit_leave_request(
    p_employee_id BIGINT, p_approver_id BIGINT, p_leave_type VARCHAR,
    p_start_date DATE, p_end_date DATE, p_reason TEXT
)
LANGUAGE plpgsql AS $$
BEGIN
    INSERT INTO leave_requests (employee_id, approver_id, leave_type, start_date, end_date, reason)
    VALUES (p_employee_id, p_approver_id, p_leave_type, p_start_date, p_end_date, p_reason);
END;
$$;

CREATE OR REPLACE PROCEDURE sp_record_attendance(
    p_employee_id BIGINT, p_attendance_date DATE, p_check_in TIME, p_check_out TIME, p_status VARCHAR
)
LANGUAGE plpgsql AS $$
BEGIN
    INSERT INTO attendance (employee_id, attendance_date, check_in, check_out, status)
    VALUES (p_employee_id, p_attendance_date, p_check_in, p_check_out, p_status)
    ON CONFLICT (employee_id, attendance_date)
    DO UPDATE SET check_in = EXCLUDED.check_in, check_out = EXCLUDED.check_out, status = EXCLUDED.status;
END;
$$;

CREATE OR REPLACE PROCEDURE sp_calculate_monthly_payroll(
    p_employee_id BIGINT, p_payroll_month DATE, p_basic_salary NUMERIC,
    p_allowances NUMERIC DEFAULT 0, p_deductions NUMERIC DEFAULT 0
)
LANGUAGE plpgsql AS $$
BEGIN
    INSERT INTO payroll (employee_id, payroll_month, basic_salary, hra, allowances, deductions, payment_status)
    VALUES (p_employee_id, date_trunc('month', p_payroll_month)::date, p_basic_salary, p_basic_salary * 0.40, p_allowances, p_deductions, 'Pending')
    ON CONFLICT (employee_id, payroll_month)
    DO UPDATE SET basic_salary = EXCLUDED.basic_salary, hra = EXCLUDED.hra,
                  allowances = EXCLUDED.allowances, deductions = EXCLUDED.deductions,
                  payment_status = 'Pending', paid_on = NULL;
END;
$$;

CREATE OR REPLACE PROCEDURE sp_assign_asset_to_employee(
    p_employee_id BIGINT, p_asset_id BIGINT, p_assigned_on DATE, p_condition_on_issue VARCHAR DEFAULT 'Good'
)
LANGUAGE plpgsql AS $$
BEGIN
    INSERT INTO employee_assets (employee_id, asset_id, assigned_on, condition_on_issue)
    VALUES (p_employee_id, p_asset_id, p_assigned_on, p_condition_on_issue);
    UPDATE assets SET status = 'Assigned' WHERE asset_id = p_asset_id;
END;
$$;

-- Triggers.
CREATE OR REPLACE FUNCTION fn_set_employee_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    NEW.updated_at := CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_set_employee_updated_at
BEFORE UPDATE ON employees
FOR EACH ROW EXECUTE FUNCTION fn_set_employee_updated_at();

CREATE OR REPLACE FUNCTION fn_validate_leave_request()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    IF NEW.end_date < NEW.start_date THEN
        RAISE EXCEPTION 'Leave end date cannot be earlier than start date';
    END IF;
    IF NEW.approver_id IS NOT NULL AND NEW.approver_id = NEW.employee_id THEN
        RAISE EXCEPTION 'Employee cannot approve their own leave request';
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_validate_leave_request
BEFORE INSERT OR UPDATE ON leave_requests
FOR EACH ROW EXECUTE FUNCTION fn_validate_leave_request();

CREATE OR REPLACE FUNCTION fn_prevent_overlapping_asset_assignment()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM employee_assets ea
        WHERE ea.asset_id = NEW.asset_id
          AND ea.employee_asset_id <> COALESCE(NEW.employee_asset_id, -1)
          AND ea.returned_on IS NULL
          AND NEW.returned_on IS NULL
    ) THEN
        RAISE EXCEPTION 'Asset % is already assigned', NEW.asset_id;
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_prevent_overlapping_asset_assignment
BEFORE INSERT OR UPDATE ON employee_assets
FOR EACH ROW EXECUTE FUNCTION fn_prevent_overlapping_asset_assignment();

CREATE OR REPLACE FUNCTION fn_update_project_assignment_count()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
DECLARE
    v_project_id BIGINT;
BEGIN
    v_project_id := COALESCE(NEW.project_id, OLD.project_id);
    UPDATE projects p
    SET current_assignment_count = (
        SELECT COUNT(*) FROM employee_project_assignments epa
        WHERE epa.project_id = v_project_id
          AND (epa.assigned_to IS NULL OR epa.assigned_to >= CURRENT_DATE)
    )
    WHERE p.project_id = v_project_id;
    RETURN COALESCE(NEW, OLD);
END;
$$;

CREATE TRIGGER trg_update_project_assignment_count
AFTER INSERT OR UPDATE OR DELETE ON employee_project_assignments
FOR EACH ROW EXECUTE FUNCTION fn_update_project_assignment_count();

CREATE OR REPLACE FUNCTION fn_compute_attendance_hours()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    IF NEW.check_in IS NOT NULL AND NEW.check_out IS NOT NULL THEN
        NEW.total_hours := ROUND((EXTRACT(EPOCH FROM (NEW.check_out - NEW.check_in)) / 3600)::numeric, 2);
    ELSIF NEW.status IN ('Absent','Holiday') THEN
        NEW.total_hours := 0;
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_compute_attendance_hours
BEFORE INSERT OR UPDATE ON attendance
FOR EACH ROW EXECUTE FUNCTION fn_compute_attendance_hours();

COMMIT;

-- 25 SQL Practice Queries: Beginner to Advanced.

-- 1. List all active employees with department and designation.
SELECT employee_code, employee_name, department_name, designation FROM vw_employee_directory WHERE employment_status = 'Active';

-- 2. Count employees by department.
SELECT d.department_name, COUNT(e.employee_id) AS employee_count FROM departments d LEFT JOIN employees e ON e.department_id = d.department_id GROUP BY d.department_name ORDER BY employee_count DESC;

-- 3. Find employees located in Bengaluru.
SELECT employee_code, employee_name, email, office_name FROM vw_employee_directory WHERE city = 'Bengaluru';

-- 4. Show all projects for a specific client.
SELECT c.client_name, p.project_code, p.project_name, p.status FROM clients c JOIN projects p ON p.client_id = c.client_id WHERE c.client_id = 1;

-- 5. List employees with Expert proficiency skills.
SELECT e.employee_code, e.first_name || ' ' || e.last_name AS employee_name, s.skill_name FROM employee_skills es JOIN employees e ON e.employee_id = es.employee_id JOIN skills s ON s.skill_id = es.skill_id WHERE es.proficiency_level = 'Expert';

-- 6. Find total monthly payroll cost.
SELECT payroll_month, SUM(net_salary) AS total_net_salary FROM payroll GROUP BY payroll_month;

-- 7. Show employees who were absent at least once in January 2026.
SELECT DISTINCT e.employee_code, e.first_name || ' ' || e.last_name AS employee_name FROM attendance a JOIN employees e ON e.employee_id = a.employee_id WHERE a.status = 'Absent' AND a.attendance_date BETWEEN DATE '2026-01-01' AND DATE '2026-01-31';

-- 8. List current manager for each employee.
SELECT employee_code, employee_name, manager_code, manager_name FROM vw_employee_hierarchy ORDER BY employee_code;

-- 9. Find project allocation count by status.
SELECT status, COUNT(*) AS project_count FROM projects GROUP BY status ORDER BY project_count DESC;

-- 10. List all assets currently assigned to employees.
SELECT e.employee_code, e.first_name || ' ' || e.last_name AS employee_name, a.asset_tag, a.asset_type, ea.assigned_on FROM employee_assets ea JOIN employees e ON e.employee_id = ea.employee_id JOIN assets a ON a.asset_id = ea.asset_id WHERE ea.returned_on IS NULL;

-- 11. Find departments whose payroll cost exceeds 2,000,000 for a month.
SELECT department_name, payroll_month, total_net_salary FROM vw_payroll_cost_by_department WHERE total_net_salary > 2000000;

-- 12. Rank employees by average performance rating.
SELECT e.employee_code, e.first_name || ' ' || e.last_name AS employee_name, ROUND(AVG(pr.rating),2) AS avg_rating, RANK() OVER (ORDER BY AVG(pr.rating) DESC) AS rating_rank FROM performance_reviews pr JOIN employees e ON e.employee_id = pr.employee_id GROUP BY e.employee_code, employee_name;

-- 13. Find employees assigned to more than 3 projects.
SELECT e.employee_code, e.first_name || ' ' || e.last_name AS employee_name, COUNT(*) AS project_count FROM employee_project_assignments epa JOIN employees e ON e.employee_id = epa.employee_id GROUP BY e.employee_code, employee_name HAVING COUNT(*) > 3 ORDER BY project_count DESC;

-- 14. Calculate billable allocation by department.
SELECT d.department_name, SUM(epa.allocation_percent) AS billable_allocation FROM employee_project_assignments epa JOIN employees e ON e.employee_id = epa.employee_id JOIN departments d ON d.department_id = e.department_id WHERE epa.billable = TRUE GROUP BY d.department_name ORDER BY billable_allocation DESC;

-- 15. Find employees without any skill record.
SELECT e.employee_code, e.first_name || ' ' || e.last_name AS employee_name FROM employees e LEFT JOIN employee_skills es ON es.employee_id = e.employee_id WHERE es.employee_id IS NULL;

-- 16. Show training completion rate by program.
SELECT tp.program_name, COUNT(et.employee_training_id) AS enrollments, ROUND(100.0 * COUNT(*) FILTER (WHERE et.status = 'Completed') / NULLIF(COUNT(et.employee_training_id),0),2) AS completion_rate FROM training_programs tp LEFT JOIN employee_training et ON et.training_program_id = tp.training_program_id GROUP BY tp.program_name ORDER BY completion_rate DESC NULLS LAST;

-- 17. Find clients with active project budgets above average.
SELECT c.client_name, SUM(p.budget) AS active_budget FROM clients c JOIN projects p ON p.client_id = c.client_id WHERE p.status = 'Active' GROUP BY c.client_name HAVING SUM(p.budget) > (SELECT AVG(budget) FROM projects WHERE status = 'Active');

-- 18. Get employee attendance percentage for January 2026.
SELECT e.employee_code, e.first_name || ' ' || e.last_name AS employee_name, ROUND(100.0 * COUNT(*) FILTER (WHERE a.status IN ('Present','Work From Home','Half Day')) / COUNT(*),2) AS attendance_percent FROM attendance a JOIN employees e ON e.employee_id = a.employee_id WHERE a.attendance_date BETWEEN DATE '2026-01-01' AND DATE '2026-01-31' GROUP BY e.employee_code, employee_name ORDER BY attendance_percent DESC;

-- 19. Find managers with direct report counts.
SELECT m.employee_code AS manager_code, m.first_name || ' ' || m.last_name AS manager_name, COUNT(em.employee_id) AS direct_reports FROM employee_managers em JOIN employees m ON m.employee_id = em.manager_id WHERE em.effective_to IS NULL GROUP BY m.employee_code, manager_name ORDER BY direct_reports DESC;

-- 20. Identify overallocated employees with more than 100 percent active allocation.
SELECT e.employee_code, e.first_name || ' ' || e.last_name AS employee_name, SUM(epa.allocation_percent) AS active_allocation FROM employee_project_assignments epa JOIN employees e ON e.employee_id = epa.employee_id WHERE epa.assigned_to IS NULL OR epa.assigned_to >= CURRENT_DATE GROUP BY e.employee_code, employee_name HAVING SUM(epa.allocation_percent) > 100 ORDER BY active_allocation DESC;

-- 21. Use a CTE to find top skill categories by certified employees.
WITH certified AS (SELECT s.skill_category, COUNT(DISTINCT es.employee_id) AS certified_employees FROM employee_skills es JOIN skills s ON s.skill_id = es.skill_id WHERE es.certified = TRUE GROUP BY s.skill_category) SELECT * FROM certified ORDER BY certified_employees DESC;

-- 22. Find each department's highest paid employee.
SELECT department_name, employee_code, employee_name, net_salary FROM (SELECT d.department_name, e.employee_code, e.first_name || ' ' || e.last_name AS employee_name, p.net_salary, ROW_NUMBER() OVER (PARTITION BY d.department_id ORDER BY p.net_salary DESC) AS rn FROM payroll p JOIN employees e ON e.employee_id = p.employee_id JOIN departments d ON d.department_id = e.department_id) x WHERE rn = 1;

-- 23. Find employees whose rating improved from H1 to H2 2025.
WITH review_scores AS (SELECT employee_id, AVG(rating) FILTER (WHERE review_period_start = DATE '2025-01-01') AS h1_rating, AVG(rating) FILTER (WHERE review_period_start = DATE '2025-07-01') AS h2_rating FROM performance_reviews GROUP BY employee_id) SELECT e.employee_code, e.first_name || ' ' || e.last_name AS employee_name, h1_rating, h2_rating FROM review_scores rs JOIN employees e ON e.employee_id = rs.employee_id WHERE h2_rating > h1_rating;

-- 24. Recursive query to show management chain for one employee.
WITH RECURSIVE chain AS (SELECT e.employee_id, e.employee_code, e.first_name || ' ' || e.last_name AS employee_name, em.manager_id, 1 AS level_no FROM employees e LEFT JOIN employee_managers em ON em.employee_id = e.employee_id AND em.effective_to IS NULL WHERE e.employee_id = 120 UNION ALL SELECT m.employee_id, m.employee_code, m.first_name || ' ' || m.last_name, em.manager_id, c.level_no + 1 FROM chain c JOIN employees m ON m.employee_id = c.manager_id LEFT JOIN employee_managers em ON em.employee_id = m.employee_id AND em.effective_to IS NULL WHERE c.manager_id IS NOT NULL) SELECT * FROM chain ORDER BY level_no;

-- 25. Advanced utilization query combining project, attendance, and payroll data.
WITH allocation AS (SELECT employee_id, SUM(allocation_percent) AS allocation_percent FROM employee_project_assignments WHERE assigned_to IS NULL OR assigned_to >= CURRENT_DATE GROUP BY employee_id), hours AS (SELECT employee_id, SUM(total_hours) AS jan_hours FROM attendance WHERE attendance_date BETWEEN DATE '2026-01-01' AND DATE '2026-01-31' GROUP BY employee_id) SELECT e.employee_code, e.first_name || ' ' || e.last_name AS employee_name, d.department_name, COALESCE(a.allocation_percent,0) AS allocation_percent, COALESCE(h.jan_hours,0) AS jan_hours, p.net_salary, ROUND(p.net_salary / NULLIF(COALESCE(h.jan_hours,0),0),2) AS cost_per_recorded_hour FROM employees e JOIN departments d ON d.department_id = e.department_id LEFT JOIN allocation a ON a.employee_id = e.employee_id LEFT JOIN hours h ON h.employee_id = e.employee_id LEFT JOIN payroll p ON p.employee_id = e.employee_id AND p.payroll_month = DATE '2026-01-01' ORDER BY cost_per_recorded_hour DESC NULLS LAST;
